import turtle
angle = 45
syam_turtle = turtle.Turtle()
syam_turtle.forward(100)
syam_turtle.left(angle)
syam_turtle.forward(100)
syam_turtle.left(angle)
syam_turtle.forward(100)
syam_turtle.left(angle)
syam_turtle.forward(100)
syam_turtle.left(angle)
syam_turtle.forward(100)
syam_turtle.left(angle)
syam_turtle.forward(100)
syam_turtle.left(angle)
syam_turtle.forward(100)
syam_turtle.left(angle)
syam_turtle.forward(100)
syam_turtle.left(angle)
